### ISSUE TITLE
Stable release for Qt5

### ISSUE THREAD

**Issue by tomyun** [realnc/hugor#2]
It seems the current stable version requires Qt4, while there has been some work going on in this repository to support Qt5. Given its last release was 4 years ago, do you have any plan for releasing a new stable build with Qt5 anytime soon?

Homebrew package manager for macOS currently provides 1.0 version of hugor (Homebrew/homebrew-games#365), but needs transition to Qt5 before Homebrew completely removes Qt4 dependencies due to its obsolete support on the latest macOS (Homebrew/homebrew-core#1705).

**Comment by realnc** [comment]
I have no ETA yet for the next release.

**Comment by tomyun** [comment]
FYI, `hugor` formula has been removed from `homebrew-games` tap for now (Homebrew/homebrew-games#752). Feel free to let us know when hugor becomes Qt5-ready, then we'd love to bring it back.

**Comment by realnc** [comment]
I will close this issue when I prepare a new version. So just monitor the issue.

**Comment by realnc** [comment]
Closing, since version 2.0 is now out. It only supports Qt 5.5 and up (5.12 is in homebrew so that's not a problem) and SDL 2.

If you intend to create a formula for it, the deps are:

pkg-config
Qt Widgets
SDL 2
FluidSynth >=2.0.4 (1.x does *not* work)
libmpg123
libsndfile
libopenmpt
libVLC >= 3.0.0
libVLC ffmpeg plugin

There's an uncommon dependency for OPL3 emulation: [libADLMIDI](https://github.com/Wohlstand/libADLMIDI), but current Git master is needed. This is why OPL3 emulation is disabled by default and must be enabled explicitly with `CONFIG+=adlmidi`.

If Homebrew can not provide libVLC + the ffmpeg plugin, then video support must be disabled with `CONFIG+=disable-video`. (There's a gstreamer option for video support, but it's not useful since current gstreamer versions have huge issues with the video format used in Hugo games. There's also a QtMultimedia backend, but it's an experiment, not documented, and mostly doesn't work because QtMultimedia isn't very suitable for this.)

Note that the binary macOS release of Hugor ships with both video and OPL3 emulation enabled, so the Homebrew version is unfortunately going to be a degraded version of the app. Hopefully libVLC can be put in Homebrew in the future, and libADLMIDI will see a suitable stable release in the future.
